version: '3'

services:
  api:
    container_name: boilerplate_api
    image: wricke/bexs_challenge
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start:dev"
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - ./.env